Add systemd service unit and modernize init.d script
Co-authored-by: pkathmann88 <8090598+pkathmann88@users.noreply.github.com>

diff --git a/motion-detection/mario/mario b/motion-detection/mario/mario
--- a/motion-detection/mario/mario
+++ b/motion-detection/mario/mario
@@ -1,31 +1,126 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides: mario
-# Required-Start: $syslog
-# Required-Stop: $syslog
+# Required-Start: $syslog $remote_fs
+# Required-Stop: $syslog $remote_fs
 # Default-Start: 2 3 4 5
 # Default-Stop: 0 1 6
-# Short-Description: mario motion detection
-# Description:
+# Short-Description: Mario motion detection service
+# Description: Motion detection system that plays Mario-themed sounds
+#              when motion is detected via PIR sensor on GPIO23
 ### END INIT INFO
- 
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Mario Motion Detection Service"
+NAME=mario
+DAEMON=/usr/bin/python3
+DAEMON_ARGS="/usr/local/bin/mario.py"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    
+    # Check if already running
+    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
+        return 1
+    fi
+    
+    # Start the daemon
+    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --make-pidfile \
+        --background --exec "$DAEMON" -- $DAEMON_ARGS \
+        || return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    
+    # Send SIGTERM for graceful shutdown
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+        --pidfile "$PIDFILE" --exec "$DAEMON"
+    RETVAL="$?"
+    
+    # Remove PID file
+    rm -f "$PIDFILE"
+    
+    return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+    start-stop-daemon --stop --signal 1 --quiet --pidfile "$PIDFILE" \
+        --exec "$DAEMON"
+    return 0
+}
+
 case "$1" in
     start)
-        echo "mario wird gesucht"
-        # Starte Programm
-        nohup /usr/bin/luigi > /var/log/motion.log &
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        do_start
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
         ;;
     stop)
-        echo "suche nach mario wird beendet"
-        # Beende Programm
-	#PID=$(ps aux | grep pir.py | grep -v grep | grep -v sudo | awk '{print $2}')
-	#kill $PID
-	touch /tmp/stop_mario
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+    status)
+        status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
+        ;;
+    restart|force-reload)
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_stop
+        case "$?" in
+            0|1)
+                do_start
+                case "$?" in
+                    0) log_end_msg 0 ;;
+                    1) log_end_msg 1 ;; # Old process is still running
+                    *) log_end_msg 1 ;; # Failed to start
+                esac
+                ;;
+            *)
+                # Failed to stop
+                log_end_msg 1
+                ;;
+        esac
         ;;
     *)
-        echo "Benutzt: /etc/init.d/mario {start|stop}"
-        exit 1
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+        exit 3
         ;;
 esac
- 
+
 exit 0
